# Generated by Django 3.2.20 on 2023-08-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_listentry_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listentry',
            name='finished',
        ),
        migrations.AddField(
            model_name='listentry',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
